/* GERADOR DE DADOS */
/* Usei o site generatedata.com ele me da a opcao de gerar um data set do jeito ai de baixo :D */

select * from professor;

INSERT INTO `professor` (`nome`,`email`) VALUES ("Callum","placerat@arcuimperdiet.ca"),("Cooper","est.Nunc@estmollis.ca");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Winter","justo@lacusAliquam.org"),("Mikayla","Phasellus.libero@enimnonnisi.edu");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Angela","Fusce.diam.nunc@Curabitur.com"),("Dorothy","neque@Vivamusrhoncus.net");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Alvin","et.tristique.pellentesque@nislNullaeu.edu"),("Zachery","sed.libero@Curabiturutodio.co.uk");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Ella","ultrices.iaculis.odio@sed.co.uk"),("Craig","nibh@utlacusNulla.ca");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Yoshio","et@mauris.ca"),("Asher","venenatis@vitaeerat.edu");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Damon","odio@nibh.org"),("Illana","et.euismod@vulputate.ca");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Hilda","in@sapienimperdietornare.net"),("Karleigh","justo.sit@mifringillami.org");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Regina","metus.In@atiaculisquis.org"),("Shelly","odio@vestibulumloremsit.net");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Maile","Donec.tincidunt@gravidamolestiearcu.org"),("Tatiana","fermentum.vel.mauris@non.com");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Britanni","id.ante@duisemperet.ca"),("Ivana","amet@dapibus.edu");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Amery","ut@quam.net"),("Wyatt","orci@ut.org");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Madonna","Sed.eu@morbi.com"),("Ila","quis@semNulla.ca");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Illiana","parturient@AeneanmassaInteger.org"),("Vincent","tincidunt.Donec.vitae@rhoncusProinnisl.edu");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Ian","magna.sed.dui@eu.ca"),("Austin","amet.ultricies.sem@gravidamaurisut.co.uk");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Jade","ipsum@ametmetusAliquam.co.uk"),("Lacy","lectus.a.sollicitudin@luctus.net");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Lewis","pretium.aliquet.metus@nequetellus.com"),("Tyrone","Etiam@Inornaresagittis.ca");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Martena","molestie.orci@aliquameuaccumsan.ca"),("Blaze","non.quam@molestie.org");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Paloma","ultrices@sociisnatoquepenatibus.edu"),("Vaughan","at.nisi.Cum@aliquamenim.co.uk");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Holly","Sed.molestie.Sed@a.org"),("Nora","Nulla@atvelitCras.com");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Sasha","est.Nunc@cursusdiam.edu"),("Marcia","porttitor@eunibh.com");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Freya","placerat.orci@magnisdis.net"),("Leslie","nec.orci@acurna.com");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Gannon","Donec@cursus.com"),("Xantha","risus@egetlacusMauris.com");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Celeste","senectus@pellentesque.edu"),("Kendall","consectetuer@Pellentesquehabitant.org");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Garrett","Nullam.ut@ligulaelit.co.uk"),("Lars","aliquet.Phasellus@ipsumSuspendisse.co.uk");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Daryl","id@vel.org"),("Hakeem","elit@semperrutrum.net");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Kay","eget@Nuncmauris.co.uk"),("Alexandra","Suspendisse@egestasAliquam.co.uk");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Dillon","nec.tellus.Nunc@atnisi.ca"),("David","id.sapien.Cras@Duisa.com");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Ishmael","fermentum.metus.Aenean@Aeneaneget.co.uk"),("Shannon","ipsum.dolor@eleifendCras.org");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Dakota","dis@ut.edu"),("Shannon","felis.orci@iaculis.co.uk");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Abel","odio.Phasellus@quisaccumsanconvallis.org"),("Maxwell","velit.Quisque.varius@dignissim.ca");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Eliana","Pellentesque@tinciduntorciquis.ca"),("Tara","netus@acurnaUt.ca");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Gloria","est.congue@luctusetultrices.ca"),("Shelly","magna@adipiscingelitAliquam.com");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Harding","elementum.dui@Morbi.ca"),("Jayme","dictum.placerat@scelerisquenequeNullam.ca");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Jena","nisl.arcu@pharetranibh.org"),("Deirdre","arcu.Vestibulum@atpretiumaliquet.com");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Thor","enim@consectetuermaurisid.co.uk"),("Kylie","iaculis.quis.pede@arcuNuncmauris.com");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Wyatt","massa@nulla.edu"),("Bert","metus.In@mollislectuspede.org");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Boris","faucibus.Morbi.vehicula@Donec.co.uk"),("Hadley","dolor.sit.amet@vestibulum.net");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Nerea","ligula.tortor@massaMauris.com"),("Lana","Duis.at.lacus@Sed.co.uk");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Stacey","sagittis.augue.eu@loremDonec.edu"),("Jason","magna.Lorem.ipsum@diam.ca");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Nasim","Nulla.tempor@dictummagnaUt.co.uk"),("Dorothy","aliquam.enim.nec@Suspendissecommodotincidunt.co.uk");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Owen","ut.quam@estNuncullamcorper.co.uk"),("Renee","elementum@vitaeerat.edu");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Karen","id.ante.Nunc@interdumNunc.co.uk"),("Cassandra","ornare.Fusce@anteblandit.org");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Fredericka","fringilla.euismod.enim@egestasDuisac.org"),("Yardley","Aliquam.erat.volutpat@euaugueporttitor.ca");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Baker","aptent@nasceturridiculusmus.edu"),("Mannix","ut.nisi@placerataugueSed.net");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Maisie","sodales.Mauris@loremtristiquealiquet.org"),("Illiana","malesuada@aliquetvel.ca");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Walker","Suspendisse.eleifend.Cras@tincidunt.com"),("Mohammad","ac.feugiat.non@magnaUt.net");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Maggy","rutrum.Fusce@aliquetsemut.net"),("Yuli","ut.erat@netuset.edu");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Evan","imperdiet.dictum.magna@amet.edu"),("Hiram","consectetuer@Vestibulum.net");
INSERT INTO `professor` (`nome`,`email`) VALUES ("Elaine","Donec.egestas@diameu.net"),("Rhona","Cras.eget.nisi@non.org");
